baseURL = "https://shptecheu.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "SHP"
theme = "meghna-hugo"
summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"
  
# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 4

    [[menu.nav]]
    name = "Testimonials"
    URL = "testimonials"
    weight = 5

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 6

# Site params
[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Your future"
author = "SHP"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/banner.jpg"
    icon = "tf-ion-cloud"
    heading = "Cloudify your operations"
    content= "Take your business to the cloud in seconds"
    btn = true
    btnText="Explore"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "Extensive Experience and Wide range of Business Domains"
    content = "Put your I.T. operations on auto pilot, while we make sure your business runs smoothly with peace of mind in a secure environment."
    btnURL = "#services"
    btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = true
    URL="#pricing"
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Happy Clients"
        icon = "tf-ion-android-happy"
        count = "120"

        [[params.counter.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-archive"
        count = "30"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "45"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"

    
    # counter
    [params.counter1]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter1.counterItem]]
        title = "Happy Clients"
        icon = "tf-ion-android-happy"
        count = "120"

        [[params.counter1.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-archive"
        count = "30"

        [[params.counter1.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "45"

        [[params.counter1.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"

    # footer
    [params.footer]
        copyright = "SHP"
        copyrightURL = "http://www.shp.com/privacy"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "#"
